[[redirects]]
  from = "/exp"
  to = "https://joshuasisley.exprealty.com"
  status = 301
  force = true
  query = {path = ":path"}
  conditions = {Language = ["en"], Country = ["US"], Role = ["admin"]}
